import ArticleBody from "@/components/ArticleBody"
import ArticleLinkBtn from "@/components/ArticleLinkBtn"
import Head from "next/head"

const Article = () => {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ArticleBody/>
    <ArticleLinkBtn/>
  </>
  )
}

export default Article;